### ISSUE TITLE
Symlink Python3 to Python no longer necessary

### ISSUE THREAD

**Issue by WessellUrdata** [CodingMarkus/Hack#2]
During the image build process, Step 4 fails.
```
STEP 4/26: RUN ln -s /usr/bin/python3 /usr/bin/python
ln: /usr/bin/python: File exists
```
I guess this is probably a relic from the past when the Python2 package was the one providing the `python` command.

**Comment by CodingMarkus** [comment]
I'm not sure who provided `/usr/bin/python` in the past, I just noticed that the Python 3 package itself did not, and I'm not too familiar with how Alpine handles this situation. 

For example, when using MacPorts on the Mac, you can install as many different Python versions as you want and none of them will directly provide `/usr/bin/python`, instead you have to run `port select --set python python<ver>` and make one of them the "system Python" and the package manager will create the appropriate symlinks for it. Only if you are installing Python for the first time, will this happen automatically, as you will only have one version installed.

Maybe Alpine has a similar management system, but since all I needed was one `/usr/bin/python`, I just created the symlink myself, which may not have been the right thing to do, but it worked.

A safe way to be compatible with different Alpine versions would probably be

```
RUN sh -c 'test -e /usr/bin/python || ln -s /usr/bin/python3 /usr/bin/python'
```

as it will create the symlink if missing and do nothing otherwise.

**Comment by CodingMarkus** [comment]
I'm going to fix this at the end of the week, and also make sure the whole thing still works, since I haven't used it in a while. 

I only created this fork because I disliked some of the standard glyphs and wanted to build the font myself with modifications. However, I didn't have access to a suitable build system and didn't want to mess up my production system with all the dependencies. So I came up with the idea to do it all in a Docker container.

**Comment by WessellUrdata** [comment]
Alright, take your time.

Installing Alpine's `python3` package should do. [Link to Alpine repo](https://pkgs.alpinelinux.org/package/edge/main/x86/python3). I've also found a few other bugs with the current Dockerfile, where `pip install` won't work. I tried modifying the Dockerfile to set up a venv, but it didn't quite work since I was trying to get it working at 4am. I may try submitting a new PR if I get it working. In any case, thanks for making the repo.

Btw, I just found my new go-to font, [Commit Mono](https://commitmono.com/), so don't worry too much about it.

**Comment by CodingMarkus** [comment]
Everything seems to be working again. I had to make a few changes. 

The main ones are

- Remove symlinking as it should not be needed anymore.

- Allow PIP to modify system Python. Otherwise, it would have required a lot of modifications to make everything work with a virtual Python environment, and since the sole purpose of this Docker container is to build the Hack font, I have no problem with PIP touching, overwriting, or possibly destroying system-wide packages, as long as the packages needed to build the font work correctly.

- Add a new build dependency to the docker image that apparently wasn't needed before, but without fontmake (actually one of its dependencies) refused to build.

- Switched woff2 from the source-foundry fork back to the original Google repo, since the macOS bug fixed in the fork was fixed in the parent repo about a year ago, and the source-foundry fork contains another bug that causes `ar` to fail on Alpine Linux, and that bug didn't even exist in the parent repo.


I also added a new shell script called `docker` which automates the whole docker setup and build process quite a bit. See `./docker help` for details.
